// Usage: node scripts/find-repos.mjs [--limit 100] [--out repos.txt] [--dry-run]
// Optional: GITHUB_TOKEN=... for higher rate limits (unauthenticated search is ~10 requests/minute).
// Discovers public repos via the GitHub search API (no git, no clones) and writes "owner/repo" lines.
import { writeFileSync } from "node:fs";

// HEURISTICS, NOT PROOF: a repo matching these queries merely *mentions* an AI builder and looks
// MERN-ish. It may be hand-written, and AI-generated repos that say nothing will be missed.
// Edit freely. Each entry is a GitHub repository-search query; the filters below are appended.
const QUERIES = [
  "topic:mern lovable",
  "topic:mern bolt.new",
  "topic:mern cursor in:readme",
  "topic:mern v0 in:readme",
  "topic:mern \"generated with\" in:readme",
  "express mongoose lovable in:readme",
  "express mongoose bolt.new in:readme",
  "express mongoose \"built with cursor\" in:readme",
  "express mongoose \"generated with\" in:readme",
  "mern \"vibe coding\" in:readme,description",
  "mern \"ai-generated\" in:readme,description",
];
const LANGUAGES = ["JavaScript", "TypeScript"];
const MAX_SIZE_KB = 50 * 1024; // 50 MB
const PUSHED_WITHIN_DAYS = 365;
const MAX_WAIT_S = 90; // never sleep longer than this on a rate limit; give up instead
const MAX_RETRIES = 2;

const args = process.argv.slice(2);
const flag = (n) => args.includes(n);
const opt = (n, d) => (args.includes(n) ? args[args.indexOf(n) + 1] : d);
const limit = Number(opt("--limit", 100));
const out = opt("--out", "repos.txt");
const dry = flag("--dry-run");
if (!Number.isInteger(limit) || limit < 1) throw new Error("--limit must be a positive integer");

const token = process.env.GITHUB_TOKEN;
const headers = { Accept: "application/vnd.github+json", "User-Agent": "ship-check-find-repos" };
if (token) headers.Authorization = `Bearer ${token}`;
const gap = token ? 2000 : 7000; // stay under the search limit (30/min authed, 10/min anon)
const since = new Date(Date.now() - PUSHED_WITHIN_DAYS * 864e5).toISOString().slice(0, 10);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

class RateLimited extends Error {}

async function search(q) {
  const url = `https://api.github.com/search/repositories?${new URLSearchParams({
    q, sort: "updated", order: "desc", per_page: "100",
  })}`;
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(url, { headers });
    if (res.ok) return (await res.json()).items ?? [];
    if (res.status !== 403 && res.status !== 429)
      throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    const retryAfter = Number(res.headers.get("retry-after"));
    const reset = Number(res.headers.get("x-ratelimit-reset"));
    const remaining = res.headers.get("x-ratelimit-remaining");
    let wait = retryAfter || (reset ? reset - Date.now() / 1000 + 1 : 60);
    wait = Math.max(1, Math.ceil(wait));
    const hint = token ? "" : " Set GITHUB_TOKEN for higher limits.";
    if (attempt >= MAX_RETRIES || wait > MAX_WAIT_S || (res.status === 403 && remaining !== "0" && !retryAfter))
      throw new RateLimited(`GitHub rate limit / denied (HTTP ${res.status}, needs ${wait}s).${hint}`);
    console.log(`Rate limited (HTTP ${res.status}); waiting ${wait}s (retry ${attempt + 1}/${MAX_RETRIES}).${hint}`);
    await sleep(wait * 1000);
  }
}

const queries = QUERIES.flatMap((q) =>
  LANGUAGES.map((l) => `${q} language:${l} fork:false archived:false size:<${MAX_SIZE_KB} pushed:>${since}`));
console.log(`${token ? "Authenticated" : "Unauthenticated (slow, ~10 req/min)"}; ${queries.length} queries; limit ${limit}`);
if (dry) queries.forEach((q) => console.log(`  query: ${q}`));

const found = new Set();
let aborted = false;
for (const q of queries) {
  if (found.size >= limit * 3) break; // plenty of candidates; avoid burning quota
  try {
    for (const r of await search(q))
      // re-check locally in case the API qualifiers were loosened
      if (!r.fork && !r.archived && !r.private && r.size <= MAX_SIZE_KB && r.pushed_at >= since) found.add(r.full_name);
    console.log(`${found.size} unique so far`);
  } catch (e) {
    console.error(`Stopping early: ${e.message}`);
    aborted = true;
    break;
  }
  if (dry && found.size >= 5) break;
  await sleep(gap);
}

// ponytail: sorted alphabetically (stable/reproducible), not by relevance; the cap truncates by name
const list = [...found].sort((a, b) => a.localeCompare(b, "en")).slice(0, limit);
if (dry) {
  console.log(`\nDry run: would write ${list.length} repos to ${out}. First results:`);
  console.log(list.slice(0, 10).join("\n"));
} else if (list.length) {
  writeFileSync(out, `# generated by find-repos.mjs; heuristic candidates, not proof of AI generation\n${list.join("\n")}\n`);
  console.log(`Wrote ${list.length} repos to ${out}${aborted ? " (partial: rate limited)" : ""}`);
} else {
  console.error("No repos found; nothing written.");
  process.exitCode = 1;
}
